---
- include: database.yml
- include: nginx.yml

- name: Create web root
  file: path="{{ www_root }}"
        owner="{{ deploy_user }}"
        group=www-data
        mode=0755
        state=directory
  with_dict: wordpress_sites

- name: Setup system cron
  cron: name="{{ item.key }} WordPress cron"
        minute="*/15"
        user=www-data
        job="curl -s {{ item.value.env.wp_siteurl }}/wp-cron.php"
        cron_file="wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: wordpress_sites
  when: item.value.system_cron | default(False) == True
