---
- name: Setup deploy group
  group: name="{{ deploy_group }}" state=present

- name: Setup deploy user
  user: name="{{ deploy_user }}"
        group="{{ deploy_group }}"
        groups="{{ deploy_groups }}"
        state=present
        shell=/bin/bash

- name: Add deploy user to www-data group
  user: name="{{ deploy_user }}" groups=www-data state=present append=yes
